# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [1]:
%run initialise.py

Exception: File `'initialise.py'` not found.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [2]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [3]:
print("numpy version",np.__version__)

numpy version 2.2.4


#### 3. Create a null vector of size 10 (★☆☆)

In [4]:
null_vector=np.zeros(10)
print(null_vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [5]:
array=np.array([1,3,4,5,6,8,19])
memorysize=array.nbytes
print(memorysize)

56


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [6]:
help(np.add)

Help on ufunc in module numpy:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])
    
    Add arguments element-wise.
    
    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` 

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [7]:
null_vector=np.zeros(10)
null_vector[4]=1
print(null_vector)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [9]:
vector=np.arange(10,50)
print(vector)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [11]:
vector=np.arange(10,50)
vector=vector[::-1]
print(vector)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [13]:
matrix=np.arange(9).reshape(3,3)
matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [28]:
array=np.array([1,3,0,0,4,0])
non_zero=np.nonzero(array)
print(non_zero)


(array([0, 1, 4]),)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [26]:
idnt_metrix=np.eye(3)
print(idnt_metrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [27]:
random_array=np.random.rand(3,3,3)
print(random_array)

[[[0.34069224 0.03988677 0.85544456]
  [0.00522979 0.74287746 0.06523462]
  [0.12970616 0.64968554 0.11227088]]

 [[0.0067945  0.49916922 0.35183969]
  [0.48221174 0.34797761 0.55773217]
  [0.37415002 0.14558306 0.75451672]]

 [[0.58235477 0.17441946 0.47570934]
  [0.7046458  0.5877057  0.15910942]
  [0.29663138 0.06330168 0.48674622]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [30]:
random_array=np.random.rand(3,3,3)
print(random_array)
print(random_array.min())
print(random_array.max())

[[[0.14323921 0.17075463 0.44835466]
  [0.5675997  0.15435262 0.1293651 ]
  [0.73279566 0.24298944 0.79057813]]

 [[0.6659413  0.59615279 0.89001415]
  [0.1971807  0.11484737 0.48997915]
  [0.68341903 0.34165983 0.21762912]]

 [[0.02219421 0.27163464 0.0301627 ]
  [0.92992555 0.5922763  0.61907185]
  [0.66465853 0.80598545 0.54183236]]]
0.022194214753091912
0.9299255481603471


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [31]:
random_vector=np.random.rand(30)
mean_value=random_vector.mean()
print(random_vector)
print(mean_value)

[0.9891698  0.20333233 0.02945294 0.08703668 0.04437631 0.12719028
 0.02183245 0.50656886 0.57708456 0.06146768 0.63143403 0.48443002
 0.71580649 0.77689897 0.26948832 0.55745694 0.46467485 0.62421366
 0.56775893 0.18293008 0.92226897 0.78711527 0.53901713 0.20296764
 0.72661385 0.10918106 0.61719409 0.74785731 0.78573969 0.01629259]
0.4458950594635025


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [37]:
array=np.zeros((5,5))
array[0,:]=1
array[-1,:]=1
array[:,0]=1
array[:,-1]=1
print(array)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [44]:
array=np.ones((3,3))
border_array=np.pad(array,pad_width=1,mode='constant',constant_values=0)
print(border_array)

[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

nan
false
false

In [ ]:

print(np.inf>np.nan)
print(np.nan-np.nan)
print(np.nan in set([np.nan]))
print(.3==3*0.1)

False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [3]:
matrix=np.zeros((5,5),dtype=int)
value=[1,2,3,4]
for i in range(1,5):
    matrix[i,i-1]=value[i-1]
    print(matrix)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 0 0]]
[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [9]:
chk_brd=np.zeros((8,8), dtype=int)
chk_brd[1::2,::2]=1
chk_brd[::2,1::2]=1
print(chk_brd)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [3]:
shape=(6,7,8)
flattened_index =100-1
index=np.unravel_index(flattened_index,shape)
print(f"The index (x,y,z) of the 100 th element is :{index}")


The index (x,y,z) of the 100 th element is :(np.int64(1), np.int64(5), np.int64(3))


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [7]:

pattern=np.array([[0,1],[1,0]])
chk_brd=np.tile(pattern,(4,4))
print(chk_brd)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [10]:
random_matrix=np.random.random((5,5))
normalized_matrix=(random_matrix-np.min(random_matrix))/(np.max(random_matrix)-np.min(random_matrix))
print("original Matrix :")
print(random_matrix)
print("\n Normalized matrix")
print(normalized_matrix)

original Matrix :
[[0.17712486 0.3851801  0.34945882 0.65746113 0.86994965]
 [0.76846457 0.75429927 0.74580223 0.35301783 0.65023146]
 [0.11986003 0.2273443  0.83310247 0.12444742 0.85558521]
 [0.53112962 0.63582412 0.51820662 0.8027889  0.16306539]
 [0.20505571 0.71850945 0.02701642 0.06683737 0.8486275 ]]

 Normalized matrix
[[0.17807868 0.4249016  0.38252425 0.74791773 1.        ]
 [0.87960483 0.86280007 0.85271974 0.38674643 0.73934093]
 [0.11014349 0.23765569 0.95628695 0.11558567 0.98295898]
 [0.59804642 0.72224902 0.58271543 0.92032494 0.16139947]
 [0.21121399 0.8203414  0.         0.04724094 0.97470481]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [16]:
rbga_dtype = np.dtype([('R', np.uint8), ('G', np.uint8), ('B', np.uint8), ('A', np.uint8)])
color = np.array([(255, 0, 0, 255), (0, 255, 0, 255), (0, 0, 255, 255), (255, 255, 0, 255)], dtype=rbga_dtype)
print(color)



[(255,   0,   0, 255) (  0, 255,   0, 255) (  0,   0, 255, 255)
 (255, 255,   0, 255)]


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [3]:
matrix_1=np.random.rand(5,3)
matrix_2=np.random.rand(3,2)
result=np.dot(matrix_1,matrix_2)
print(matrix_1)
print(matrix_2)
print(result)

[[0.94259047 0.02041107 0.50186215]
 [0.62498886 0.17137186 0.37440982]
 [0.60319491 0.3746021  0.2267312 ]
 [0.99748127 0.4333438  0.53127979]
 [0.87890255 0.26187762 0.67409319]]
[[0.62187226 0.75868546]
 [0.3455219  0.5077052 ]
 [0.84512693 0.67533277]]
[[1.01736055 1.06441644]
 [0.76429979 0.81402757]
 [0.69616005 0.80094164]
 [1.21903456 1.33557609]
 [1.20674388 1.25500444]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [7]:
ary=np.array([1,4,5,6,7,9,7,3])
ary[(ary>=3) &(ary<=8)] *=-1
print(ary)

[ 1 -4 -5 -6 -7  9 -7 -3]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [11]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

10
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

NameError: name 'z' is not defined

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [15]:
np.array(0)/np.array(0)
np.array(0)//np.array(0)
np.array([np.nan]).astype(int).astype(float)



C:\Users\romal\AppData\Local\Temp\ipykernel_4544\4081235388.py:1: RuntimeWarning: invalid value encountered in divide
  np.array(0)/np.array(0)
C:\Users\romal\AppData\Local\Temp\ipykernel_4544\4081235388.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0)//np.array(0)
C:\Users\romal\AppData\Local\Temp\ipykernel_4544\4081235388.py:3: RuntimeWarning: invalid value encountered in cast
  np.array([np.nan]).astype(int).astype(float)


array([-9.22337204e+18])

#### 29. How to round away from zero a float array ? (★☆☆)

In [21]:
float_array=np.array([-2.3,-1.5,1.2,3.7,0.0])
rounded_array=np.sign(float_array)*np.ceil(np.abs(float_array))
print(rounded_array)

[-3. -2.  2.  4.  0.]


#### 30. How to find common values between two arrays? (★☆☆)

In [3]:
ary1=[1,2,3,4,5,6]
ary2=[9,8,6,5,4,3]
cmn_value=list(set(ary1) & set(ary2))

print("common value :",cmn_value)

common value : [3, 4, 5, 6]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [ ]:
import warnings
import numpy as np
warning.fi
lterwarning("ignore")
array=np.array([1,2,3])
print(np.divide(array,0))

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [5]:
np.sqrt(-1) == np.emath.sqrt(-1)   

NameError: name 'np' is not defined

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [2]:
from datetime import datetime,timedelta
today=datetime.now()
tomorrow=today+timedelta(days=1)
yesterday=today-timedelta(days=1)
print(today)
print(tomorrow)
print(yesterday)

2025-03-31 11:08:47.154098
2025-04-01 11:08:47.154098
2025-03-30 11:08:47.154098


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)


In [3]:
start_date=datetime(2016,7,1)
end_date=datetime(2016,8,1)
current_date=start_date
while current_date<end_date:
    print(current_date.strftime('%d-%m-%y'))
    current_date+= timedelta(days=1)

01-07-16
02-07-16
03-07-16
04-07-16
05-07-16
06-07-16
07-07-16
08-07-16
09-07-16
10-07-16
11-07-16
12-07-16
13-07-16
14-07-16
15-07-16
16-07-16
17-07-16
18-07-16
19-07-16
20-07-16
21-07-16
22-07-16
23-07-16
24-07-16
25-07-16
26-07-16
27-07-16
28-07-16
29-07-16
30-07-16
31-07-16


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [9]:
# 1 
import numpy as np
array=np.random.random(10)*10
integer_part=np.floor(array)
print(integer_part)
#2

import numpy as np
array=np.random.rand(10)*10
integer_part=np.floor(array)
print(integer_part)

[4. 5. 2. 5. 8. 5. 0. 7. 8. 4.]
[1. 6. 5. 6. 5. 4. 6. 6. 7. 2.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [19]:
#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)
import numpy as np

matrix = np.tile(np.arange(5), (5, 1))  # Create a 5x5 matrix with rows ranging from 0 to 4
print(matrix)


[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]



#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [23]:
def generate_integer():
    for i in range(10):
        yield i
    
array=np.fromiter(generate_integer(),dtype=int)
print(array)    

[0 1 2 3 4 5 6 7 8 9]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [24]:
vector=np.linspace(0,1,12)[1:-1]
print(vector)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [25]:
ran_vec=np.random.rand(10)
sort_vec=np.sort(ran_vec)
print(ran_vec)
print(sort_vec)

[0.61269824 0.08493378 0.77711132 0.76097472 0.41791963 0.12246842
 0.587684   0.33473601 0.8481551  0.11980871]
[0.08493378 0.11980871 0.12246842 0.33473601 0.41791963 0.587684
 0.61269824 0.76097472 0.77711132 0.8481551 ]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [26]:
array=np.array([1,2,3,4,6,9])
total=sum(array)
print(total)

25


#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [27]:
A=np.random.rand(5)
B=np.random.rand(5)
equal=np.array_equal(A,B)
print(equal)

False


#### 43. Make an array immutable (read-only) (★★☆)

In [29]:
array=np.random.rand(5)
array.flags.writeable=False
print(array)
array[0]=12
print(array)

[0.7589607  0.62700381 0.94045245 0.13907687 0.91598976]


ValueError: assignment destination is read-only

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [32]:
cartesian=np.random.rand(10,2)*10
r=np.sqrt(cartesian[:,1]**2+ cartesian[:,1]**2)
theta=np.arctan2(cartesian[:,1],cartesian[:,0])
polar=np.column_stack((r,theta))
print(cartesian)
print("\n")
print(polar)

[[0.20308802 7.24817524]
 [4.29232671 4.44270689]
 [0.49943845 8.50479531]
 [3.85855412 3.42659191]
 [1.56385305 7.52885893]
 [7.38794641 2.70689252]
 [0.70692137 8.23810872]
 [8.74582606 3.93057071]
 [0.3348835  5.72519811]
 [4.02638772 4.59199954]]


[[10.25046773  1.54278446]
 [ 6.28293634  0.80261222]
 [12.02759687  1.51213936]
 [ 4.84593275  0.72617395]
 [10.64741441  1.36599412]
 [ 3.82812412  0.35120362]
 [11.65044508  1.4851949 ]
 [ 5.55866641  0.42237354]
 [ 8.09665281  1.51236999]
 [ 6.49406803  0.85093268]]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [36]:
ran_vec=np.random.rand(10)
max_index=np.argmax(ran_vec)
ran_vec[max_index]=0
print(ran_vec)

[0.79473431 0.83329284 0.46603401 0.10218503 0.89998502 0.15872038
 0.32580359 0.18910771 0.         0.95008924]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [37]:
import numpy as np
dtype=[('x',float),('y',float)]
x=np.linspace(0,1,5)
y=np.linspace(0,1,5)
x,y=np.meshgrid(x,y)
structured_array=np.zeros(x.shape,dtype=dtype)
structured_array['x']=x
structured_array['y']=y
print(structured_array)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [41]:
X=np.random.rand(5)
Y=np.random.rand(5)

C=1/(X[:,None]-Y[None,:])
print("Array X:", X)
print("Array Y:", Y)
print("Cauchy Matrix C:")
print(C)

Array X: [0.01269291 0.60077403 0.31081303 0.898206   0.69243637]
Array Y: [0.8215778  0.2222971  0.65921311 0.73171484 0.17193732]
Cauchy Matrix C:
[[ -1.23626985  -4.77089699  -1.54674208  -1.39077815  -6.27965505]
 [ -4.52890828   2.64216894 -17.1118381   -7.63703831   2.33188992]
 [ -1.95784843  11.29740143  -2.87026341  -2.375851     7.20068353]
 [ 13.05002557   1.47948932   4.18422486   6.00632507   1.37690091]
 [ -7.74344883   2.12702926  30.09938814 -25.45924007   1.92123309]]


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [8]:
import numpy as np
print("integer types")
for dtype in [np.int8,np.int16,np.int32,np.int64,np.uint16,np.uint32,np.uint64] :
    info =np.iinfo(dtype)
    print(f"{dtype.__name__}-min:{info.min},max:{info.max}")
    print("\nfloat_point types:")
    for dtype in [np.float16,np.float32,np.float64] :
        info =np.finfo(dtype)
        print(f"{dtype.__name__}-min:{info.min},max:{info.max}")

integer types
int8-min:-128,max:127

float_point types:
float16-min:-65504.0,max:65504.0
float32-min:-3.4028234663852886e+38,max:3.4028234663852886e+38
float64-min:-1.7976931348623157e+308,max:1.7976931348623157e+308
int16-min:-32768,max:32767

float_point types:
float16-min:-65504.0,max:65504.0
float32-min:-3.4028234663852886e+38,max:3.4028234663852886e+38
float64-min:-1.7976931348623157e+308,max:1.7976931348623157e+308
int32-min:-2147483648,max:2147483647

float_point types:
float16-min:-65504.0,max:65504.0
float32-min:-3.4028234663852886e+38,max:3.4028234663852886e+38
float64-min:-1.7976931348623157e+308,max:1.7976931348623157e+308
int64-min:-9223372036854775808,max:9223372036854775807

float_point types:
float16-min:-65504.0,max:65504.0
float32-min:-3.4028234663852886e+38,max:3.4028234663852886e+38
float64-min:-1.7976931348623157e+308,max:1.7976931348623157e+308
uint16-min:0,max:65535

float_point types:
float16-min:-65504.0,max:65504.0
float32-min:-3.4028234663852886e+38,max:3.402

#### 49. How to print all the values of an array? (★★☆)

In [14]:
arr=np.arange(81).reshape(9,9)

print(arr)

[[ 0  1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16 17]
 [18 19 20 21 22 23 24 25 26]
 [27 28 29 30 31 32 33 34 35]
 [36 37 38 39 40 41 42 43 44]
 [45 46 47 48 49 50 51 52 53]
 [54 55 56 57 58 59 60 61 62]
 [63 64 65 66 67 68 69 70 71]
 [72 73 74 75 76 77 78 79 80]]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)


In [4]:
import numpy as np
#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)
vector = np.array([1, 3, 8, 15, 20])
scalar = 15
index=np.abs(vector-scalar).argmin()
closest_value=vector[index]
print(closest_value)

15


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [7]:
import numpy as np
dtype = [('position', [('x', 'f4'), ('y', 'f4')]), 
         ('color', [('r', 'u1'), ('g', 'u1'), ('b', 'u1')])]

array=np.zeros(5,dtype=dtype)
array[0]=((0.0,1.0),(255,0,0))
array[1]=((1.0,2.0),(0,255,0))
array[2]=((2.0,3.0),(0,0,255))
print(array)

[((0., 1.), (255,   0,   0)) ((1., 2.), (  0, 255,   0))
 ((2., 3.), (  0,   0, 255)) ((0., 0.), (  0,   0,   0))
 ((0., 0.), (  0,   0,   0))]


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [8]:

import numpy as np
from scipy.spatial.distance import cdist

# Create a random vector with shape (100, 2)
random_vector = np.random.rand(100, 2)

# Calculate the distances between all pairs of points
distances = cdist(random_vector, random_vector)

# Print the distance matrix
print("Pairwise distances:")
print(distances)


Pairwise distances:
[[0.         0.39925019 0.47656464 ... 0.07439348 0.48669907 0.2815025 ]
 [0.39925019 0.         0.65936117 ... 0.47359354 0.18249347 0.67215205]
 [0.47656464 0.65936117 0.         ... 0.47589707 0.8266411  0.59885142]
 ...
 [0.07439348 0.47359354 0.47589707 ... 0.         0.55583784 0.21109785]
 [0.48669907 0.18249347 0.8266411  ... 0.55583784 0.         0.72643106]
 [0.2815025  0.67215205 0.59885142 ... 0.21109785 0.72643106 0.        ]]


#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [11]:
float_array=np.array([1.1,2.2,3.3,4.4],dtype=np.float32)
float_array[:]=float_array.astype(np.int32)
print(float_array)

[1. 2. 3. 4.]


#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [1]:
import numpy as np

# Create a NumPy array
array = np.array([[1, 2, 3], [4, 5, 6]])

# Use ndenumerate to iterate with indices and values
for index, value in np.ndenumerate(array):
    print(f"Index: {index}, Value: {value}")


Index: (0, 0), Value: 1
Index: (0, 1), Value: 2
Index: (0, 2), Value: 3
Index: (1, 0), Value: 4
Index: (1, 1), Value: 5
Index: (1, 2), Value: 6


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [2]:
import numpy as np

# Define the size of the array and standard deviation
size = 5  # e.g., a 5x5 array
sigma = 1.0  # Standard deviation of the Gaussian

# Create the coordinate grid
x, y = np.meshgrid(np.linspace(-1, 1, size), np.linspace(-1, 1, size))

# Compute the 2D Gaussian-like values
gaussian = np.exp(-(x**2 + y**2) / (2 * sigma**2))

# Normalize the array (optional)
gaussian /= gaussian.sum()

print(gaussian)


[[0.02324684 0.03382395 0.03832756 0.03382395 0.02324684]
 [0.03382395 0.04921356 0.05576627 0.04921356 0.03382395]
 [0.03832756 0.05576627 0.06319146 0.05576627 0.03832756]
 [0.03382395 0.04921356 0.05576627 0.04921356 0.03382395]
 [0.02324684 0.03382395 0.03832756 0.03382395 0.02324684]]


#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [3]:
import numpy as np

# Define the size of the array and the number of elements to place
rows, cols = 5, 5  # Size of the 2D array (e.g., 5x5)
p = 5  # Number of elements to randomly place

# Create an empty array filled with zeros
array = np.zeros((rows, cols), dtype=int)

# Generate random unique positions for the p elements
indices = np.random.choice(rows * cols, p, replace=False)

# Place the elements in the array
for index in indices:
    x, y = divmod(index, cols)
    array[x, y] = 1  # You can replace 1 with the desired value

print(array)


[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 1 0 1 1]
 [0 0 1 0 0]
 [0 0 0 0 0]]


#### 58. Subtract the mean of each row of a matrix (★★☆)

In [4]:
import numpy as np

# Create a sample matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Subtract the mean of each row
row_means = matrix.mean(axis=1, keepdims=True)  # Compute the mean for each row
result = matrix - row_means  # Subtract the mean from each row

print(result)


[[-1.  0.  1.]
 [-1.  0.  1.]
 [-1.  0.  1.]]


#### 59. How to sort an array by the nth column? (★★☆)

In [5]:
import numpy as np

# Create a sample array
array = np.array([[4, 2, 7],
                  [1, 5, 6],
                  [9, 0, 8]])

# Specify the column index (nth column, e.g., n=1 for the second column)
n = 1

# Sort the array by the nth column
sorted_array = array[array[:, n].argsort()]

print("Original array:")
print(array)
print("\nSorted array by column", n + 1, ":")
print(sorted_array)



Original array:
[[4 2 7]
 [1 5 6]
 [9 0 8]]

Sorted array by column 2 :
[[9 0 8]
 [4 2 7]
 [1 5 6]]


#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [6]:
import numpy as np

# Example 2D array
array = np.array([[0, 1, 0],
                  [0, 0, 0],
                  [0, 3, 0]])

# Check for null (all-zero) columns
null_columns = np.all(array == 0, axis=0)

# Identify which columns are null
has_null_columns = np.any(null_columns)

print("Null columns:", null_columns)
print("Has null columns:", has_null_columns)


Null columns: [ True False  True]
Has null columns: True


#### 61. Find the nearest value from a given value in an array (★★☆)

In [7]:
import numpy as np

# Example array and target value
array = np.array([10, 20, 30, 40, 50])
target = 33

# Find the nearest value
nearest_value = array[np.abs(array - target).argmin()]

print("Nearest value to", target, "is", nearest_value)


Nearest value to 33 is 30


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [8]:
import numpy as np

# Define the two arrays
array1 = np.array([[1, 2, 3]])  # Shape (1, 3)
array2 = np.array([[4], [5], [6]])  # Shape (3, 1)

# Create an iterator for the sum
it = np.nditer([array1, array2, None])  # Prepare output buffer as `None`

# Iterate and compute the sum
for a, b, c in it:
    c[...] = a + b  # Perform element-wise addition

# Get the result array
result = it.operands[2]

print("Result:")
print(result)


Result:
[[5 6 7]
 [6 7 8]
 [7 8 9]]


#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [9]:
import numpy as np

class NamedArray(np.ndarray):
    def __new__(cls, input_array, name="Unnamed"):
        # Create an instance of the subclass
        obj = np.asarray(input_array).view(cls)
        # Add the new attribute
        obj.name = name
        return obj

    def __array_finalize__(self, obj):
        if obj is None:
            return
        # Ensure the `name` attribute is inherited
        self.name = getattr(obj, 'name', "Unnamed")

# Example usage
data = np.array([[1, 2, 3], [4, 5, 6]])
named_array = NamedArray(data, name="MyArray")

print(named_array)
print("Array Name:", named_array.name)


[[1 2 3]
 [4 5 6]]
Array Name: MyArray


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [10]:
import numpy as np

# Define the input vector X, index list I, and the target array F
X = np.array([1, 2, 3, 4, 5])  # Vector to accumulate values from
I = np.array([0, 1, 0, 1, 2])  # Index list
F = np.zeros(3)  # Target array initialized with zeros

# Accumulate values from X into F based on indices in I
np.add.at(F, I, X)

print("Accumulated array F:", F)


Accumulated array F: [4. 6. 5.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

In [11]:
import numpy as np

# Define the input vector X, index list I, and the target array F
X = np.array([1, 2, 3, 4, 5])  # Vector to accumulate values from
I = np.array([0, 1, 0, 1, 2])  # Index list
F = np.zeros(3)  # Target array initialized with zeros

# Accumulate values from X into F based on indices in I
np.add.at(F, I, X)

print("Accumulated array F:", F)



Accumulated array F: [4. 6. 5.]


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [12]:
import numpy as np

# Example image of shape (w, h, 3) with dtype=ubyte
w, h = 4, 4  # Dimensions of the image
image = np.random.randint(0, 256, (w, h, 3), dtype=np.uint8)  # Random image

# Reshape the image into a 2D array where each row is a color (R, G, B)
flattened_image = image.reshape(-1, 3)

# Find unique rows (unique colors) and count them
unique_colors = np.unique(flattened_image, axis=0)
num_unique_colors = unique_colors.shape[0]

print("Number of unique colors:", num_unique_colors)



Number of unique colors: 16


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [13]:
import numpy as np

# Create a sample 4D array
array = np.random.rand(2, 3, 4, 5)  # Shape: (2, 3, 4, 5)

# Sum over the last two axes (axis 2 and 3)
result = array.sum(axis=(-2, -1))

print("Shape of original array:", array.shape)
print("Shape after summing over the last two axes:", result.shape)
print("Result:\n", result)


Shape of original array: (2, 3, 4, 5)
Shape after summing over the last two axes: (2, 3)
Result:
 [[11.66610285 10.93558182  8.11038425]
 [11.58505208 10.13343171 11.08426587]]


#### 69. How to get the diagonal of a dot product? (★★★)

In [14]:
import numpy as np

# Define the vector D and the subset indices S
D = np.array([1, 2, 3, 4, 5, 6])  # Data vector
S = np.array([0, 1, 0, 1, 2, 2])  # Subset indices

# Compute the sums of subsets using np.bincount
subset_sums = np.bincount(S, weights=D)

# Compute the counts of elements in each subset
subset_counts = np.bincount(S)

# Compute the means of subsets
subset_means = subset_sums / subset_counts

print("Subset means:", subset_means)


Subset means: [2.  3.  5.5]


#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [15]:
import numpy as np

# Original vector
original_vector = np.array([1, 2, 3, 4, 5])

# Define the new size considering 3 zeros between each element
new_size = len(original_vector) * 4 - 3  # Each element + 3 zeros

# Create a new array filled with zeros
new_vector = np.zeros(new_size, dtype=int)

# Assign original values to every 4th position
new_vector[::4] = original_vector

print("New vector with interleaved zeros:")
print(new_vector)


New vector with interleaved zeros:
[1 0 0 0 2 0 0 0 3 0 0 0 4 0 0 0 5]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

In [16]:
import numpy as np

# Example arrays
array1 = np.random.rand(5, 5, 3)  # Shape (5, 5, 3)
array2 = np.random.rand(5, 5)  # Shape (5, 5)

# Reshape array2 to broadcast along the last dimension of array1
result = array1 * array2[:, :, np.newaxis]

print("Resulting array shape:", result.shape)


Resulting array shape: (5, 5, 3)


#### 72. How to swap two rows of an array? (★★★)

In [17]:
import numpy as np

# Example 2D array
array = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

# Swap row 0 (first row) and row 2 (third row)
array[[0, 2]] = array[[2, 0]]

print("Array after swapping rows:")
print(array)




Array after swapping rows:
[[7 8 9]
 [4 5 6]
 [1 2 3]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

In [18]:
import numpy as np

# Example set of triplets describing 10 triangles (each triplet defines a triangle)
triplets = np.array([
    [0, 1, 2],
    [0, 2, 3],
    [1, 2, 4],
    [2, 3, 4],
    [0, 1, 5],
    [0, 5, 6],
    [1, 4, 7],
    [4, 7, 8],
    [6, 5, 9],
    [9, 7, 8]
])

# Find all edges (line segments) from the triangles
edges = []
for triplet in triplets:
    edges.append(tuple(sorted([triplet[0], triplet[1]])))
    edges.append(tuple(sorted([triplet[1], triplet[2]])))
    edges.append(tuple(sorted([triplet[2], triplet[0]])))

# Use a set to find unique edges
unique_edges = set(edges)

print("Unique line segments composing all triangles:")
print(unique_edges)


Unique line segments composing all triangles:
{(np.int64(3), np.int64(4)), (np.int64(0), np.int64(2)), (np.int64(8), np.int64(9)), (np.int64(0), np.int64(5)), (np.int64(5), np.int64(6)), (np.int64(4), np.int64(8)), (np.int64(5), np.int64(9)), (np.int64(0), np.int64(1)), (np.int64(2), np.int64(4)), (np.int64(1), np.int64(2)), (np.int64(1), np.int64(5)), (np.int64(7), np.int64(9)), (np.int64(4), np.int64(7)), (np.int64(0), np.int64(3)), (np.int64(1), np.int64(4)), (np.int64(0), np.int64(6)), (np.int64(2), np.int64(3)), (np.int64(1), np.int64(7)), (np.int64(6), np.int64(9)), (np.int64(7), np.int64(8))}


#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

In [19]:
import numpy as np

# Given sorted array C (the bincount result)
C = np.array([2, 3, 0, 1])  # Example bincount array

# Produce array A
A = np.repeat(np.arange(len(C)), C)

print("Array A:", A)
print("Bincount of A:", np.bincount(A))


Array A: [0 0 1 1 1 3]
Bincount of A: [2 3 0 1]


#### 75. How to compute averages using a sliding window over an array? (★★★)

In [20]:
import numpy as np

# Example 1D array
array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Define the sliding window size
window_size = 3

# Create a window (all elements are 1, normalized by the window size)
window = np.ones(window_size) / window_size

# Compute the sliding window averages
averages = np.convolve(array, window, mode='valid')

print("Sliding window averages:", averages)


Sliding window averages: [2. 3. 4. 5. 6. 7. 8. 9.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

In [21]:
import numpy as np

# Define the one-dimensional array
Z = np.array([1, 2, 3, 4, 5, 6, 7, 8])

# Specify the window size (number of elements per row)
window_size = 3

# Build the two-dimensional array
rows = len(Z) - window_size + 1  # Number of rows required
result = np.array([Z[i:i + window_size] for i in range(rows)])

print("Two-dimensional array:")
print(result)


Two-dimensional array:
[[1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [22]:
import numpy as np

# Example boolean array
bool_array = np.array([True, False, True, True])

# Negate the boolean in-place
bool_array[:] = ~bool_array

print("Negated boolean array:", bool_array)


Negated boolean array: [False  True False False]


#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

In [23]:
import numpy as np

# Define the sets of points P0, P1, and the point p
P0 = np.array([[0, 0], [1, 1], [2, 2]])  # Starting points of lines
P1 = np.array([[1, 0], [2, 1], [3, 3]])  # Ending points of lines
p = np.array([1, 2])  # Point for distance calculation

# Compute the distances
distances = []
for i in range(len(P0)):
    # Vector from P0 to P1
    v = P1[i] - P0[i]
    # Vector from P0 to p
    w = p - P0[i]
    # Project w onto v to find the closest point on the line
    projection = np.dot(w, v) / np.dot(v, v)
    projection = np.clip(projection, 0, 1)  # Ensure projection is within the segment
    closest_point = P0[i] + projection * v
    # Compute the distance from p to the closest point
    distance = np.linalg.norm(p - closest_point)
    distances.append(distance)

print("Distances from p to each line segment:", distances)


Distances from p to each line segment: [np.float64(2.0), np.float64(1.0), np.float64(1.0)]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

In [24]:
import numpy as np

# Define the sets of points P0, P1 (lines) and P (points)
P0 = np.array([[0, 0], [1, 1], [2, 2]])  # Starting points of lines
P1 = np.array([[1, 0], [2, 1], [3, 3]])  # Ending points of lines
P = np.array([[1, 2], [3, 1], [0, 0]])   # Set of points

# Compute distances from each point in P to each line segment (P0[i], P1[i])
distances = np.zeros((len(P), len(P0)))  # Initialize distance array

for j in range(len(P)):  # Iterate over points P[j]
    for i in range(len(P0)):  # Iterate over lines (P0[i], P1[i])
        # Line vector and vector to point
        v = P1[i] - P0[i]  # Vector from P0 to P1
        w = P[j] - P0[i]   # Vector from P0 to P[j]

        # Project w onto v to find the closest point on the line
        projection = np.dot(w, v) / np.dot(v, v)
        projection = np.clip(projection, 0, 1)  # Ensure projection is within the segment
        closest_point = P0[i] + projection * v

        # Compute the distance from P[j] to the closest point
        distances[j, i] = np.linalg.norm(P[j] - closest_point)

print("Distances from each point to each line segment:")
print(distances)


Distances from each point to each line segment:
[[2.         1.         1.        ]
 [2.23606798 1.         1.41421356]
 [0.         1.41421356 2.82842712]]


#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

In [25]:
import numpy as np

# Define the sets of points P0, P1 (lines) and P (points)
P0 = np.array([[0, 0], [1, 1], [2, 2]])  # Starting points of lines
P1 = np.array([[1, 0], [2, 1], [3, 3]])  # Ending points of lines
P = np.array([[1, 2], [3, 1], [0, 0]])   # Set of points

# Compute distances from each point in P to each line segment (P0[i], P1[i])
distances = np.zeros((len(P), len(P0)))  # Initialize distance array

for j in range(len(P)):  # Iterate over points P[j]
    for i in range(len(P0)):  # Iterate over lines (P0[i], P1[i])
        # Line vector and vector to point
        v = P1[i] - P0[i]  # Vector from P0 to P1
        w = P[j] - P0[i]   # Vector from P0 to P[j]

        # Project w onto v to find the closest point on the line
        projection = np.dot(w, v) / np.dot(v, v)
        projection = np.clip(projection, 0, 1)  # Ensure projection is within the segment
        closest_point = P0[i] + projection * v

        # Compute the distance from P[j] to the closest point
        distances[j, i] = np.linalg.norm(P[j] - closest_point)

print("Distances from each point to each line segment:")
print(distances)


Distances from each point to each line segment:
[[2.         1.         1.        ]
 [2.23606798 1.         1.41421356]
 [0.         1.41421356 2.82842712]]


#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

In [26]:
import numpy as np

# Input array
Z = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14])

# Define the window size
window_size = 4

# Generate the array R using a sliding window
R = np.array([Z[i:i + window_size] for i in range(len(Z) - window_size + 1)])

print("Generated array R:")
print(R)


Generated array R:
[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★)

In [27]:
import numpy as np

# Define a matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Compute the rank of the matrix
rank = np.linalg.matrix_rank(matrix)

print("Rank of the matrix:", rank)


Rank of the matrix: 2


#### 83. How to find the most frequent value in an array?

In [28]:
import numpy as np

# Example array
array = np.array([1, 2, 3, 4, 2, 2, 3, 1, 4, 4, 4])

# Find the most frequent value
most_frequent = np.bincount(array).argmax()

print("Most frequent value:", most_frequent)


Most frequent value: 4


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

In [29]:
import numpy as np

# Example array
array = np.array([1, 2, 3, 4, 2, 2, 3, 1, 4, 4, 4])

# Find the most frequent value
most_frequent = np.bincount(array).argmax()

print("Most frequent value:", most_frequent)


Most frequent value: 4


#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

In [31]:
import numpy as np

class SymmetricArray(np.ndarray):
    def __new__(cls, input_array):
        # Create an instance of the subclass
        obj = np.asarray(input_array).view(cls)
        return obj
    
    def __getitem__(self, indices):
        i, j = indices
        # Ensure symmetry: return the value at (i, j) or (j, i)
        return super().__getitem__((min(i, j), max(i, j)))
    
    def __setitem__(self, indices, value):
        i, j = indices
        # Ensure symmetry: set the value at (i, j) and (j, i)
        super().__setitem__((min(i, j), max(i, j)), value)

# Example usage
data = np.zeros((5, 5))  # Initialize a symmetric matrix with zeros
Z = SymmetricArray(data)

Z[2, 3] = 7  # Set value at (2, 3), automatically sets (3, 2) to the same value
print("Z[3, 2]:", Z[3, 2])  # Access (3, 2), which is the same as (2, 3)
print("Symmetric array:")
print(Z)


Z[3, 2]: 7.0
Symmetric array:
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 7. 0.]
 [0. 0. 7. 0. 0.]
 [0. 0. 0. 0. 0.]]


#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

In [32]:
import numpy as np

# Example set of p matrices (shape (p, n, n)) and p vectors (shape (p, n, 1))
p, n = 3, 4
A = np.random.rand(p, n, n)  # Set of p matrices
x = np.random.rand(p, n, 1)  # Set of p vectors

# Compute the sum of matrix products
result = np.einsum('pij,pjk->ik', A, x).squeeze()

print("Result:")
print(result)


Result:
[3.79669076 2.57926607 2.80506432 2.60187967]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

In [33]:
import numpy as np

# Create a 16x16 example array
array = np.random.rand(16, 16)

# Reshape the array into 4x4 blocks and compute the sum
block_size = 4
block_sum = array.reshape(16 // block_size, block_size, 16 // block_size, block_size).sum(axis=(1, 3))

print("Block-sum array:")
print(block_sum)


Block-sum array:
[[ 6.65445463 10.07431492  9.14614131  9.45629063]
 [ 8.40263125  7.67136085  7.62660339  7.93445524]
 [ 7.49706197  6.18019381  6.72957309 10.0656169 ]
 [ 8.18312753 10.65774768  8.8537749   8.68246296]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [35]:
import numpy as np

def game_of_life_step(board):
    """
    Perform one step of the Game of Life on the given board.
    
    Parameters:
    - board: 2D NumPy array where 1 represents a live cell and 0 represents a dead cell.
    
    Returns:
    - Updated board after one step.
    """
    # Count neighbors using convolution-like logic
    neighbors = (
        np.roll(np.roll(board, 1, 0), 1, 1) + np.roll(np.roll(board, 1, 0), -1, 1) +
        np.roll(np.roll(board, -1, 0), 1, 1) + np.roll(np.roll(board, -1, 0), -1, 1) +
        np.roll(board, 1, 0) + np.roll(board, -1, 0) +
        np.roll(board, 1, 1) + np.roll(board, -1, 1)
    )
    
    # Apply the rules of the Game of Life
    new_board = (neighbors == 3) | (board & (neighbors == 2))
    return new_board.astype(int)

# Initialize the board (10x10 grid with a random state)
np.random.seed(0)
board = np.random.randint(0, 2, (10, 10))

# Display the initial board
print("Initial board:")
print(board)

# Perform one step
board = game_of_life_step(board)

# Display the updated board
print("\nBoard after one step:")
print(board)


Initial board:
[[0 1 1 0 1 1 1 1 1 1]
 [1 0 0 1 0 0 0 0 0 1]
 [0 1 1 0 0 1 1 1 1 0]
 [1 0 1 0 1 1 0 1 1 0]
 [0 1 0 1 1 1 1 1 0 1]
 [0 1 1 1 1 0 1 0 0 1]
 [1 0 1 0 1 0 0 0 0 0]
 [1 1 0 0 0 1 1 0 1 0]
 [0 1 0 1 1 1 1 1 1 0]
 [1 1 0 0 1 0 0 1 1 0]]

Board after one step:
[[0 0 1 0 1 1 1 0 0 0]
 [0 0 0 1 0 0 0 0 0 0]
 [0 0 1 0 0 1 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 1 1 1]
 [0 0 0 0 1 0 1 1 0 0]
 [1 0 0 0 0 0 0 0 1 0]
 [0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]


#### 89. How to get the n largest values of an array (★★★)

In [36]:
import numpy as np

# Example array
array = np.array([10, 20, 5, 8, 70, 30, 100, 40])

# Number of largest values to find
n = 3

# Get the indices of the n largest values
indices = np.argpartition(array, -n)[-n:]

# Extract the n largest values
n_largest_values = array[indices]

# Optionally, sort the largest values in descending order
n_largest_values_sorted = np.sort(n_largest_values)[::-1]

print("n largest values:", n_largest_values_sorted)


n largest values: [100  70  40]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

In [37]:
import numpy as np
from itertools import product

# Example input: arbitrary number of vectors
vectors = [np.array([1, 2, 3]), np.array([4, 5]), np.array([6, 7, 8])]

# Compute the Cartesian product
cartesian_product = np.array(list(product(*vectors)))

print("Cartesian product:")
print(cartesian_product)


Cartesian product:
[[1 4 6]
 [1 4 7]
 [1 4 8]
 [1 5 6]
 [1 5 7]
 [1 5 8]
 [2 4 6]
 [2 4 7]
 [2 4 8]
 [2 5 6]
 [2 5 7]
 [2 5 8]
 [3 4 6]
 [3 4 7]
 [3 4 8]
 [3 5 6]
 [3 5 7]
 [3 5 8]]


#### 91. How to create a record array from a regular array? (★★★)

In [38]:
import numpy as np

# Example regular array
data = np.array([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9]])

# Create a record array with field names
record_array = np.core.records.fromarrays(data, names='a, b, c')

print("Record array:")
print(record_array)
print("Access field 'a':", record_array.a)


Record array:
[(1, 4, 7) (2, 5, 8) (3, 6, 9)]
Access field 'a': [1 2 3]


C:\Users\romal\AppData\Local\Temp\ipykernel_14640\2723749191.py:9: DeprecationWarning: numpy.core is deprecated and has been renamed to numpy._core. The numpy._core namespace contains private NumPy internals and its use is discouraged, as NumPy internals can change without warning in any release. In practice, most real-world usage of numpy.core is to access functionality in the public NumPy API. If that is the case, use the public NumPy API. If not, you are using NumPy internals. If you would still like to access an internal attribute, use numpy._core.records.
  record_array = np.core.records.fromarrays(data, names='a, b, c')


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

In [39]:
import numpy as np

# Create a large vector Z
Z = np.random.rand(10**6)  # Vector with 1 million elements

# Method 1: Using NumPy's power function
method1 = np.power(Z, 3)

# Method 2: Using element-wise multiplication
method2 = Z * Z * Z

# Method 3: Using NumPy's ufunc for power (** operator)
method3 = Z ** 3

# Verify that all methods produce the same result
print(np.allclose(method1, method2))  # Should print: True
print(np.allclose(method1, method3))  # Should print: True


True
True


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

In [42]:
import numpy as np

# Define A and B
A = np.random.randint(0, 10, (8, 3))  # Example array A (8x3)
B = np.random.randint(0, 10, (2, 2))  # Example array B (2x2)

# Find rows of A that contain all elements of each row of B
rows = []
for b in B:
    # Check if all elements of row b in B exist in any row of A
    matches = np.all([np.isin(b[0], A), np.isin(b[1], A)], axis=0)
    rows.append(np.where(matches)[0])

print("Matrix A:")
print(A)
print("\nMatrix B:")
print(B)
print("\nRows of A containing all elements of each row in B:")
print(rows)


ValueError: Calling nonzero on 0d arrays is not allowed. Use np.atleast_1d(scalar).nonzero() instead. If the context of this error is of the form `arr[nonzero(cond)]`, just use `arr[cond]`.

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)


In [44]:
import numpy as np

# Example 10x3 matrix
matrix = np.random.randint(0, 5, (10, 3))  # Random integers between 0 and 4

# Identify rows with unequal values
unequal_rows = matrix[np.any(matrix != matrix[:, 0][:, np.newaxis], axis=1)]

print("Original matrix:")
print(matrix)
print("\nRows with unequal values:")
print(unequal_rows)



Original matrix:
[[4 4 1]
 [4 4 2]
 [4 3 3]
 [1 1 1]
 [2 4 4]
 [4 2 1]
 [1 0 0]
 [1 4 3]
 [3 1 2]
 [2 3 2]]

Rows with unequal values:
[[4 4 1]
 [4 4 2]
 [4 3 3]
 [2 4 4]
 [4 2 1]
 [1 0 0]
 [1 4 3]
 [3 1 2]
 [2 3 2]]


### 95 convert a vector ints into a matrix binary representation

In [50]:
import numpy as np

def vector_to_binary_matrix(vector, bits=None):
    """
    Convert a vector of integers into a matrix of binary representations.
    
    Parameters:
    - vector: 1D array of integers.
    - bits: Number of bits for binary representation (optional). If None, it automatically calculates based on the maximum integer.
    
    Returns:
    - Binary matrix: 2D array where each row represents the binary representation of an integer.
    """
    # Determine the number of bits if not provided
    if bits is None:
        bits = int(np.floor(np.log2(max(vector))) + 1)

    # Convert each integer to binary and store as rows in the matrix
    binary_matrix = np.array([np.binary_repr(v, width=bits) for v in vector], dtype='U')
    binary_matrix = np.array([list(map(int, row)) for row in binary_matrix])

    return binary_matrix

# Example usage
vector = np.array([5, 10, 15])
binary_matrix = vector_to_binary_matrix(vector)

print("Original vector:")
print(vector)
print("\nBinary representation matrix:")
print(binary_matrix)


Original vector:
[ 5 10 15]

Binary representation matrix:
[[0 1 0 1]
 [1 0 1 0]
 [1 1 1 1]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

In [45]:
import numpy as np

# Example two-dimensional array
array = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [1, 2, 3],
                  [7, 8, 9],
                  [4, 5, 6]])

# Extract unique rows
unique_rows = np.unique(array, axis=0)

print("Original array:")
print(array)
print("\nUnique rows:")
print(unique_rows)


Original array:
[[1 2 3]
 [4 5 6]
 [1 2 3]
 [7 8 9]
 [4 5 6]]

Unique rows:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

In [46]:
import numpy as np

A = np.array([1, 2, 3])
B = np.array([4, 5, 6])

# Inner product using einsum
inner = np.einsum('i,i->', A, B)

print("Inner product:", inner)


Inner product: 32


#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

In [47]:
import numpy as np

A = np.array([1, 2, 3])
B = np.array([4, 5, 6])

# Inner product using einsum
inner = np.einsum('i,i->', A, B)

print("Inner product:", inner)


Inner product: 32


#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

In [48]:
import numpy as np

# Example path described by X and Y
X = np.array([0, 1, 2, 3, 4])
Y = np.array([0, 1, 0, 1, 0])

# Number of equidistant samples
num_samples = 10

# Calculate the cumulative distance along the path
distances = np.sqrt(np.diff(X)**2 + np.diff(Y)**2)
cumulative_distance = np.concatenate([[0], np.cumsum(distances)])

# Interpolate to get equidistant sample points
new_distances = np.linspace(0, cumulative_distance[-1], num_samples)
new_X = np.interp(new_distances, cumulative_distance, X)
new_Y = np.interp(new_distances, cumulative_distance, Y)

# Resulting sampled points
sampled_points = np.column_stack((new_X, new_Y))

print("Sampled points (X, Y):")
print(sampled_points)


Sampled points (X, Y):
[[0.         0.        ]
 [0.44444444 0.44444444]
 [0.88888889 0.88888889]
 [1.33333333 0.66666667]
 [1.77777778 0.22222222]
 [2.22222222 0.22222222]
 [2.66666667 0.66666667]
 [3.11111111 0.88888889]
 [3.55555556 0.44444444]
 [4.         0.        ]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)

In [49]:
import numpy as np

# Example 1D array
X = np.random.rand(100)  # Array of random numbers

# Number of bootstrap resamples
N = 1000

# Bootstrap resampling
bootstrap_means = np.array([np.mean(np.random.choice(X, size=len(X), replace=True)) for _ in range(N)])

# Compute 95% confidence intervals (percentiles 2.5 and 97.5)
lower_bound = np.percentile(bootstrap_means, 2.5)
upper_bound = np.percentile(bootstrap_means, 97.5)

print("Bootstrapped 95% confidence interval for the mean:")
print(f"Lower bound: {lower_bound}, Upper bound: {upper_bound}")


Bootstrapped 95% confidence interval for the mean:
Lower bound: 0.42886166749910487, Upper bound: 0.5462487586842053
