#Numpy basic

In [1]:
import numpy as np

Creat a vector

In [2]:
vec_row=np.array([1,2,3])
print(vec_row)

[1 2 3]


In [5]:
vec_col=np.array([[1,5],[2,7],[3,8]])
print(vec_col)

[[1 5]
 [2 7]
 [3 8]]


Matrics 

In [7]:
matrix1=np.array([[1,5],[2,7],[3,8]])
print(matrix1)

[[1 5]
 [2 7]
 [3 8]]


sparce matrix

In [8]:
from scipy import sparse
matrix1=np.array([[0,5],[2,0],[0,0]])
print(matrix1)

[[0 5]
 [2 0]
 [0 0]]


In [10]:
mat_sp=sparse.csr_matrix(matrix1)
print(mat_sp)

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 2 stored elements and shape (3, 2)>
  Coords	Values
  (0, 1)	5
  (1, 0)	2


## pre-alloation arrey

In [18]:
matrix_11=np.full(shape=(5,9),fill_value="sa71")
print(matrix_11)


[['sa71' 'sa71' 'sa71' 'sa71' 'sa71' 'sa71' 'sa71' 'sa71' 'sa71']
 ['sa71' 'sa71' 'sa71' 'sa71' 'sa71' 'sa71' 'sa71' 'sa71' 'sa71']
 ['sa71' 'sa71' 'sa71' 'sa71' 'sa71' 'sa71' 'sa71' 'sa71' 'sa71']
 ['sa71' 'sa71' 'sa71' 'sa71' 'sa71' 'sa71' 'sa71' 'sa71' 'sa71']
 ['sa71' 'sa71' 'sa71' 'sa71' 'sa71' 'sa71' 'sa71' 'sa71' 'sa71']]


In [21]:
print(vec_row[0])

1


In [22]:
vec_1=[1,2,3,4,5,6,6,7,8,8]

In [23]:
vec_1[:]

[1, 2, 3, 4, 5, 6, 6, 7, 8, 8]

In [24]:
vec_1[:3]

[1, 2, 3]

In [25]:
vec_1[3:]

[4, 5, 6, 6, 7, 8, 8]

In [26]:
vec_1[2:5]

[3, 4, 5]

In [34]:
mat_1=np.array([[1,5,7],[2,2,7],[12,3,8]])

In [35]:
mat_3[:2,:]

array([[1, 5, 7],
       [2, 2, 7]])

In [29]:
mat_3[:,:]

array([[ 1,  5,  7],
       [ 2,  2,  7],
       [12,  3,  8]])

matrix describing

In [30]:
mat_3.shape

(3, 3)

In [31]:
mat_3.size

9

In [32]:
mat_3.ndim

2

In [36]:
add_100=lambda i:2*i+100-i*i
vec_add_100=np.vectorize(add_100)
mat_2=vec_add_100(mat_1)
vec_add_100(mat_2)

array([[-9899, -6955, -3995],
       [-9700, -9700, -3995],
       [ -340, -9115, -2500]])

In [ ]:

np.min(mat_1)

In [38]:
np.max(mat_1)

np.int64(12)

In [42]:
mat_2=np.array([[101,104,105],[87,98,67],[23,87,89]])
np.max(mat_2,axis=0)

array([101, 104, 105])

In [43]:
mat_2=np.array([[101,104,105],[87,98,67],[23,87,89]])
np.max(mat_2,axis=1)

array([105,  98,  89])

In [44]:
np.mean(mat_2)

np.float64(84.55555555555556)

In [45]:
np.var(mat_2)

np.float64(597.3580246913582)

In [46]:
np.std(mat_2)

np.float64(24.440908835216383)

#reshaping  matrix

In [49]:
mat_4=np.array([[1,2,3],[1,3,4],[3,5,6],[0,0,99]])
print(mat_4)


[[ 1  2  3]
 [ 1  3  4]
 [ 3  5  6]
 [ 0  0 99]]


In [56]:
mat_4.reshape(2,-1)

array([[ 1,  2,  3,  1,  3,  4],
       [ 3,  5,  6,  0,  0, 99]])

Transpose matrix

In [58]:
mat_4.T

array([[ 1,  1,  3,  0],
       [ 2,  3,  5,  0],
       [ 3,  4,  6, 99]])

In [59]:
mat_4.flatten()

array([ 1,  2,  3,  1,  3,  4,  3,  5,  6,  0,  0, 99])

# Rank

In [60]:
np.linalg.matrix_rank(mat_4)

np.int64(3)

# diagonal matrix

In [61]:
mat_4.diagonal()

array([1, 3, 6])

In [63]:
mat_4.diagonal(offset=1)

array([2, 4])

# trace offset can be used 

In [64]:
mat_4.trace()

np.int64(10)

matrix addition and subtraction

In [69]:
mat_5=np.array([[ 1 , 2,  3],[ 1,  3,  4],[ 3,  5,  6],[ 0  ,0, 99,]])
np.add(mat_5,mat_4)

array([[  2,   4,   6],
       [  2,   6,   8],
       [  6,  10,  12],
       [  0,   0, 198]])

In [70]:
mat_6=np.array([[ 1 , 2,  3],[ 5,  3,  4],[ 3,  5,  6],[ 0  ,0, 99,]])
np.subtract(mat_6,mat_4)

array([[0, 0, 0],
       [4, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [ ]:
mat_6=np.array([[ 1 , 2,  3],[ 5,  3,  4],[ 3,  5,  6],[ 0  ,0, 99]])
np.multiply(mat_6,mat_4)

array([[   1,    4,    9],
       [   5,    9,   16],
       [   9,   25,   36],
       [   0,    0, 9801]])

In [72]:
mat_6=np.array([[ 1 , 2,  3],[ 5,  3,  4],[ 3,  5,  6],[ 0  ,0, 99,]])
np.dot(mat_6,mat_4)

ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

In [76]:
mat_4 @ mat_4

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 4 is different from 3)

In [79]:
np.linalg.inv(mat_6)

LinAlgError: Last 2 dimensions of the array must be square